### PR TITLE
Get the library working with node 12

### LINKED ISSUE #46: Failed to build with node 12.1.0
`npm install tree-sitter` failed on macOS mojave 10.14.4, with the following errors:

```
> tree-sitter@0.15.0 install /Users/zyang/node_modules/tree-sitter
> prebuild-install || node-gyp rebuild

  CC(target) Release/obj.target/tree_sitter/vendor/tree-sitter/lib/src/lib.o
  LIBTOOL-STATIC Release/tree_sitter.a
  CXX(target) Release/obj.target/tree_sitter_runtime_binding/src/binding.o
  CXX(target) Release/obj.target/tree_sitter_runtime_binding/src/conversions.o
```
```
../src/conversions.cc:105:41: error: too few arguments to function call, single
      argument 'context' was not specified
  if (std::isfinite(js_row->NumberValue())) {
                    ~~~~~~~~~~~~~~~~~~~ ^
/Users/zyang/.node-gyp/12.1.0/include/node/v8.h:2564:3: note: 'NumberValue'
      declared here
  V8_WARN_UNUSED_RESULT Maybe<double> NumberValue(Local<Context> context) const;
  ^
/Users/zyang/.node-gyp/12.1.0/include/node/v8config.h:347:31: note: expanded
      from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/conversions.cc:106:52: error: too few arguments to function call, single
      argument 'context' was not specified
    row = static_cast<uint32_t>(js_row->Int32Value());
                                ~~~~~~~~~~~~~~~~~~ ^
/Users/zyang/.node-gyp/12.1.0/include/node/v8.h:2569:3: note: 'Int32Value'
      declared here
  V8_WARN_UNUSED_RESULT Maybe<int32_t> Int32Value(Local<Context> context) const;
  ^
/Users/zyang/.node-gyp/12.1.0/include/node/v8config.h:347:31: note: expanded
      from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/conversions.cc:111:44: error: too few arguments to function call, single
      argument 'context' was not specified
  if (std::isfinite(js_column->NumberValue())) {
                    ~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/zyang/.node-gyp/12.1.0/include/node/v8.h:2564:3: note: 'NumberValue'
      declared here
  V8_WARN_UNUSED_RESULT Maybe<double> NumberValue(Local<Context> context) const;
  ^
/Users/zyang/.node-gyp/12.1.0/include/node/v8config.h:347:31: note: expanded
      from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/conversions.cc:112:58: error: too few arguments to function call, single
      argument 'context' was not specified
    column = static_cast<uint32_t>(js_column->Int32Value()) * BYTES_PER_...
                                   ~~~~~~~~~~~~~~~~~~~~~ ^
/Users/zyang/.node-gyp/12.1.0/include/node/v8.h:2569:3: note: 'Int32Value'
      declared here
  V8_WARN_UNUSED_RESULT Maybe<int32_t> Int32Value(Local<Context> context) const;
  ^
/Users/zyang/.node-gyp/12.1.0/include/node/v8config.h:347:31: note: expanded
      from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/conversions.cc:130:47: error: too few arguments to function call, single
      argument 'context' was not specified
  return Nan::Just<uint32_t>(arg->Uint32Value() * BYTES_PER_CHARACTER);
                             ~~~~~~~~~~~~~~~~ ^
/Users/zyang/.node-gyp/12.1.0/include/node/v8.h:2567:3: note: 'Uint32Value'
      declared here
  V8_WARN_UNUSED_RESULT Maybe<uint32_t> Uint32Value(
  ^
/Users/zyang/.node-gyp/12.1.0/include/node/v8config.h:347:31: note: expanded
      from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
13 warnings and 5 errors generated.
make: *** [Release/obj.target/tree_sitter_runtime_binding/src/conversions.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:196:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:256:12)
gyp ERR! System Darwin 18.5.0
gyp ERR! command "/usr/local/Cellar/node/12.1.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/zyang/node_modules/tree-sitter
gyp ERR! node -v v12.1.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
```

It seems that `conversions.cc` uses in-capatible v8 API?

### PR DESCRIPTION
**Pull request by maxbrunsfeld**
Fixes #46

There are a bunch of V8 API changes from Node 10 to Node 12.

### CODE REVIEW

**Comment by fernandocanizo** [comment]
Is this fix dead? Who should we poke that has write access?

**Comment by maxbrunsfeld** [comment]
If anyone is interested in working on this, that would be great! It may be a while before I have time to work on this further.

**Comment by bdurrani** [comment]
@maxbrunsfeld I downloaded the repo and ran `npm install`, but it looks like one of the dependencies doesn't install yet. It needs one of your [other PRs](https://github.com/atom/superstring/pull/72) merged.

Do I need superstring in order to do this work?
I can take a stab at updating this, but I'm a little new to this. Are there any contributing guidelines?

Thanks for all your work!

**Comment by drom** [comment]
@maxbrunsfeld could you estimate the amount and the nature of work needed to be done here?

**Comment by bdurrani** [comment]
> @bdurrani
> 
> That PR you linked above is now merged back in July. You should be able to continue.

The PR was merged, but looks like the changes have not been published to npm yet.

**Comment by tommai78101** [comment]
@bdurrani 
I didn't know that. 🤔

**Comment by bdurrani** [comment]
I was able to temporarily work about that by reference the git repo in the package file. But I'm now I'm just trying to understant the API and how the node bindings work. Let's see how it goes.

**Comment by bdurrani** [comment]
I'm not sure what I'm missing here. I've cleaned up any compile errors. 
But for some reason, I cant seem to create a new instance of the `Tree`.

Here is what I have:
https://github.com/bdurrani/node-tree-sitter/blob/08c1c3e4a36ed2a44b615292bf7c9894f8b2838c/src/tree.cc#L64

`Tree::NewInstance()` gets a tree pointer.
The call to `Nan::NewInstance() `works. I can confirm that Tree::New() is called and the
arguments to it were passed correctly by comparing the pointer values. 

But for some reason, the return value from` Nan::NewInstance()` returns an empty object. 

As a test, I looked at the `node-addon-examples `and modified the sample to follow
the pattern in tree-sitter
https://github.com/bdurrani/node-addon-examples/blob/f423f0390bd547230f56207bab3db279ea707289/6_object_wrap/nan/one.cc#L16

`One::NewInstance()` gets a pointer to some c++ class
It's constructor is called, and this time, the return value from` Nan::NewInstance()`
returns an object that is not empty. The code is almost identical. 

I haven't played much with node bindings before. Any ideas how I would debug by
[NewInstance()](url) is returning an empty object. I don't see any errors or anything happening. 

Any one have any suggestions?

**Comment by maxbrunsfeld** [comment]
Hey, thanks for taking a look at this @bdurrani; I appreciate you helping out. I think that your comment summarizes the problem that I was stuck on when I initially opened this PR, but unlike me, you took the time to write it out, which is very helpful.

Unfortunately, I haven't had much time to look into this lately, but I plan on spending a little time on it this week.

**Comment by bdurrani** [comment]
> Hey, thanks for taking a look at this @bdurrani; I appreciate you helping out. I think that your comment summarizes the problem that I was stuck on when I initially opened this PR, but unlike me, you took the time to write it out, which is very helpful.
> 
> Unfortunately, I haven't had much time to look into this lately, but I plan on spending a little time on it this week.

no problem @maxbrunsfeld 
I forgot to add more information. I added some extra code to look at existing exceptions and there was an error about an object being `null or undefined. But that's where I stopped since it wasn't clear what exactly was null or undefined

If there is anything I can do to help, let me know. I don't mind looking into it further.

**Comment by maxbrunsfeld** [comment]
Ok, I worked on this some more this morning and at least gotten it working on osx.

**Comment by maxbrunsfeld** [comment]
Ok, this is published in 0.15.9, but there is a problem with the prebuilt binaries: Travis seems to be [having some trouble](https://travis-ci.org/tree-sitter/node-tree-sitter/jobs/601465175#L387-L390) downloading the electron headers. 😕

**Comment by maxbrunsfeld** [comment]
Ok, prebuilt assets seem to be uploading ok for [v0.15.10](https://github.com/tree-sitter/node-tree-sitter/releases/tag/v0.15.10).
