### PR TITLE
Support Node 19 and update dependencies

### PR DESCRIPTION
**Pull request by verhovsky**

### CODE REVIEW

File: package.json [hunk 1]
```diff
@@ -15,17 +15,23 @@
...
   "devDependencies": {
-    "@types/node": "^14.14.31",
-    "chai": "^4.3.3",
-    "mocha": "^8.3.1",
-    "prebuild": "^10.0.1",
-    "superstring": "^2.4.2",
+    "@types/node": "^18.14.6",
+    "chai": "^4.3.7",
+    "mocha": "^10.2.0",
+    "node-gyp": "9.3.1",
```
Comment (verhovsky) [inline package.json:25]: This isn't strictly necessary but it lets you run the project with Python 3.11

See https://github.com/prebuild/prebuild/issues/286#issuecomment-1460871873

**Comment by verhovsky** [comment]
With these changes I was able to `npm install` on macOS (ARM) with Node 14 and Node 18, although `npm test` errors out with

```
RangeError: Incompatible language version. Compatible range: 13 - 13. Got: 14
```

**Comment by verhovsky** [comment]
After updating vendor/tree-sitter I'm able to run `npm test` too.

**Comment by verhovsky** [comment]
I couldn't figure out how to fix the CI with Windows, the last thing I tried is setting the Node version to 16 and it failed to download node to install it

```
npm ERR! gyp ERR! stack Error: 500 response downloading https://nodejs.org/download/release/v16.18.1/node-v16.18.1-headers.tar.gz
```

So I replaced the Windows with Ubuntu instead in the CI and it works... anyway, we should test Windows with #128

File: package.json [hunk 2]
```diff
@@ -15,17 +15,23 @@
...
+    "prebuild": "^11.0.4",
+    "superstring": "https://github.com/pulsar-edit/superstring#node-api-upgrade",
```
[the remark this answers is not in the document]
Comment (verhovsky) [reply package.json:27]: We could also fork and publish as `@treesitter/superstring`

File: src/conversions.cc [hunk 3]
```diff
@@ -34,7 +34,7 @@ void InitConversions(Local<Object> exports) {
     v8::Local<v8::Object> bufferView;
     bufferView = node::Buffer::New(Isolate::GetCurrent(), point_transfer_buffer, 0, 2 * sizeof(uint32_t)).ToLocalChecked();
     auto js_point_transfer_buffer = node::Buffer::Data(bufferView);
-  #elif V8_MAJOR_VERSION >= 8
+  #elif (V8_MAJOR_VERSION > 8 || (V8_MAJOR_VERSION == 8 && V8_MINOR_VERION > 3))
```
Comment (verhovsky) [inline src/conversions.cc:37]: Introduced in 8.3.9 https://github.com/v8/v8/commit/5cf02f0f207c05cebce74b1a8f2d0fe2accc7df6

**Comment by jgresty** [comment]
Keen to have this merged as the currently used version of `prebuild-install` is vulnerable to [CVE-2021-3807](https://www.cve.org/CVERecord?id=CVE-2021-3807) through its dependencies. Fixed in 7.1.1

**Comment by verhovsky** [comment]
@jgresty inefficient regexes are CVE spam, not real issues. If prebuild-install has an inefficient regex it shouldn't matter anyway because it runs once when you install the package.

The bigger problem and the reason this should really be merged/deployed is that packages that use tree-sitter-node have never worked on Node 19, which was released 5 months ago and is the default version that gets installed on macOS when you do `brew install node`. @maxbrunsfeld could you please merge/deploy this? It's good to go, the only thing left is the superstring dependency. I think we (you) should fork it if you're not able to publish new versions for their package on npm. I can also do it if you'd like.

**Review by cclauss — APPROVED** [review]

**Comment by verhovsky** [comment]
@jaisnan the reason is the `superstring` dependency:

https://github.com/tree-sitter/node-tree-sitter/pull/127/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R27

https://github.com/tree-sitter/node-tree-sitter/pull/127/files#r1130623351

It has the same `no member named 'GetContents' in 'v8::ArrayBuffer'` issue and needs to be [updated in the same way](https://github.com/atom/superstring/compare/master...curlconverter:superstring:master#diff-a08cda0f923d330e789b39db3295cee293d09932da29acf61ec1c97f9d4599b7) as `node-tree-sitter`. I guess we're waiting for someone to take the initiative to solve the problem administratively by forking it and publishing it as `@tree-sitter/superstring` or getting permission to make a new release of the `superstring` name, or to solve the problem technically by removing `superstring` as a dependency of `node-tree-sitter` (if that's a reasonable thing to do, I don't understand what it's used for so I can't say).

File: package.json (hunk 2 above)
[the remark this answers is not in the document]
Comment (verhovsky) [reply package.json]: Actually, since `superstring` is in `devDependencies`, we don't strictly need to fix it to make `tree-sitter` installable on Node 19 or 20.

**Comment by verhovsky** [comment]
@maxbrunsfeld could you merge/deploy this please? I [forked](https://github.com/curlconverter/node-tree-sitter) node-tree-sitter and deployed this code and can confirm that it works.

**Comment by NikkTod** [comment]
Could you please merge  👍

**Comment by cclauss** [comment]
@NikkTod Please
1. Click on https://github.com/tree-sitter/node-tree-sitter/pull/127/files
2. Click the `Review changes` button
3. Click `Approve`
4. Click `Submit review`.

**Review by NikkTod — APPROVED** [review]

**Comment by tthornton3-chwy** [comment]
@verhovsky looks like we got the approvals :) Could we try and merge this in, this dependency trickles its way on up to a bunch of other places that are currently borked because of it after moving to Node 20, and fixing it here at the source is a lot better of a solution :D

**Comment by TylerLeonhardt** [comment]
👋  I think maybe @maxbrunsfeld is maybe the best person to (gently) ping? I'm coming from [this tree-sitter-typescript issue](https://github.com/tree-sitter/tree-sitter-typescript/issues/244). Would love to see Node 19+ working with node-tree-sitter 🙏  so folks can build VS Code extensions with newer versions of Node.

File: src/tree.cc [hunk 4]
```diff
@@ -196,7 +196,7 @@ void Tree::GetEditedRange(const Nan::FunctionCallbackInfo<Value> &info) {
 
 void Tree::PrintDotGraph(const Nan::FunctionCallbackInfo<Value> &info) {
   Tree *tree = ObjectWrap::Unwrap<Tree>(info.This());
-  ts_tree_print_dot_graph(tree->tree_, stderr);
+  ts_tree_print_dot_graph(tree->tree_, 2);
```
Comment (verhovsky) [inline src/tree.cc:199]: This happens because of updating vendor/tree-sitter:

```
../src/tree.cc:199:3: error: no matching function for call to 'ts_tree_print_dot_graph'
  ts_tree_print_dot_graph(tree->tree_, stderr);
  ^~~~~~~~~~~~~~~~~~~~~~~
../vendor/tree-sitter/lib/include/tree_sitter/api.h:423:6: note: candidate function not viable: no known conversion from 'FILE *' (aka '__sFILE *') to 'int' for 2nd argument
void ts_tree_print_dot_graph(const TSTree *, int file_descriptor);
     ^
```

introduced in https://github.com/tree-sitter/tree-sitter/commit/97fd990822deeb3c288f4999a8410fba69f230b6

**Comment by cclauss** [comment]
Please change the title of this PR to add `18` and remove `19` which is EOL.
* https://github.com/nodejs/release#readme
