### ISSUE TITLE
SyntaxNode.text fails

### ISSUE THREAD

**Issue by MichaReiser** [tree-sitter/node-tree-sitter#22]
Calling `SyntaxNode.text` raises the following error

```
TypeError: this.input.substring is not a function
    at Tree.getTextFromString [as getText] (tree-sitter/index.js:357:21)
    at SyntaxNode.get text [as text] (tree-sitter/index.js:54:22)
```

I assume the call in the index.js should be `this.input(node.startIndex, node.endIndex)`?

**Comment by MichaReiser** [comment]
Ohh, okay.... Nope, I'm using the latest version published on npm: `"tree-sitter": "^0.13.2-0"`

I don't call the function myself. I use `node.text` and the getter then calls `tree.getTextFromString` which throws the aforementioned error message (it assumes this.input to be a string what seems not be the case).

If there is no text getter. How can I access e.g. the used identifiers?

**Comment by maxbrunsfeld** [comment]
Ok, the `.text` property should work in version `0.13.2`.

**Comment by wongjiahau** [comment]
@maxbrunsfeld But where is the documentation for it?
